// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfcealadbinizbeporhn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmY2VhbGFkYmluaXpiZXBvcmhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MDE2MDgsImV4cCI6MjA2NDE3NzYwOH0.FxiUoaKV6FCKEjiQxAyGnDAe8WQV2YCEyseqKQYJykc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);